# Generated by Django 3.0.8 on 2020-08-13 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.CharField(max_length=50)),
                ('class2', models.CharField(max_length=50)),
                ('class3', models.CharField(max_length=50)),
                ('class4', models.CharField(max_length=50)),
                ('class5', models.CharField(max_length=50)),
                ('class6', models.CharField(max_length=50)),
                ('class7', models.CharField(max_length=50)),
                ('class8', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signin.User')),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.CharField(max_length=50)),
                ('class2', models.CharField(max_length=50)),
                ('class3', models.CharField(max_length=50)),
                ('class4', models.CharField(max_length=50)),
                ('class5', models.CharField(max_length=50)),
                ('class6', models.CharField(max_length=50)),
                ('class7', models.CharField(max_length=50)),
                ('class8', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signin.User')),
            ],
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.CharField(max_length=50)),
                ('class2', models.CharField(max_length=50)),
                ('class3', models.CharField(max_length=50)),
                ('class4', models.CharField(max_length=50)),
                ('class5', models.CharField(max_length=50)),
                ('class6', models.CharField(max_length=50)),
                ('class7', models.CharField(max_length=50)),
                ('class8', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signin.User')),
            ],
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.CharField(max_length=50)),
                ('class2', models.CharField(max_length=50)),
                ('class3', models.CharField(max_length=50)),
                ('class4', models.CharField(max_length=50)),
                ('class5', models.CharField(max_length=50)),
                ('class6', models.CharField(max_length=50)),
                ('class7', models.CharField(max_length=50)),
                ('class8', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signin.User')),
            ],
        ),
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.CharField(max_length=50)),
                ('class2', models.CharField(max_length=50)),
                ('class3', models.CharField(max_length=50)),
                ('class4', models.CharField(max_length=50)),
                ('class5', models.CharField(max_length=50)),
                ('class6', models.CharField(max_length=50)),
                ('class7', models.CharField(max_length=50)),
                ('class8', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signin.User')),
            ],
        ),
    ]
